name: Build and Push Image to ECR

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Please confirm if you want to proceed with the build and push to ECR. Select 'yes' to confirm."
        required: true
        default: "no"
        type: choice
        options:
          - yes
          - no
      image_tag:
        description: "Tag for the Docker image"
        required: true
        default: "latest"
        type: string
      ecr_repository:
        description: "ECR repository name"
        required: true
        default: "tm-app"
        type: string
      aws_region:
        description: "AWS region for ECR"
        required: true
        default: "us-east-1"
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - ap-south-1
          - ap-northeast-3
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-2
          - ap-northeast-1
          - ca-central-1
          - eu-central-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-north-1
          - sa-east-1


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Check confirmation input
        if: ${{ github.event.inputs.confirmation != 'yes' }}
        run: |
          echo "Confirmation input is not 'yes'. Exiting."
          exit 1
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ github.event.inputs.ecr_repository }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          echo "Building Docker image for arm64 architecture..."
          docker buildx build --platform linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --push .