name: Terraform Destroy
on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      confirmation:
        description: "Please confirm if you want to proceed with Terraform Destroy. Select 'Yes' to confirm."
        required: true
        default: "No"
        type: choice
        options:
          - 'Yes'
          - 'No'

jobs:
  terraform-plan-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation input
        if: ${{ github.event.inputs.confirmation != 'Yes' }}
        run: |
          echo "Confirmation input is not 'yes'. Exiting."
          exit 1

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        working-directory: terraform
        run: |
          echo "Initializing Terraform..."
          terraform init
      
      - name: Terraform Destroy Plan
        working-directory: terraform
        run: |
          echo "Creating Terraform Destroy Plan..."
          terraform plan -destroy
          echo "Terraform Destroy Plan created successfully."
  
  terraform-destroy:
    runs-on: ubuntu-latest
    needs: terraform-plan-destroy
    environment: production # Requires manual approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init & Destroy
        working-directory: terraform
        run: |
          echo "Initializing Terraform..."
          terraform init
          echo "Destroying Terraform resources..."
          terraform destroy -auto-approve
          echo "Terraform destroy completed successfully."


